version: '3.8'

services:

  #Mongo properties
  mongo:
    image: mongo
    container_name: mongo_management

    ports:
      - 27017:27017

    restart: always

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}


  # RabbitMQ properties
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management

    ports:
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 5672:5672 # communication with the web management API

    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

    restart: always
